#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit JSON Lines; run script to print and write loc_export.jsonl next to this file."""

import json
import pathlib

_JSONL_ROWS: list[str] = []


def emit(locale: str, pairs: list[tuple[str, str]]) -> None:
    for key, val in pairs:
        _JSONL_ROWS.append(
            json.dumps({"locale": locale, "key": key, "value": val}, ensure_ascii=False)
        )


emit(
    "ar",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "قص"),
        ("Town", "بلدة"),
        ("create_detail_free_coloring_photo_ipad_title", "استخدم تحويل الصور"),
        ("create_detail_free_coloring_text_ipad_title", "حوّل النص\nإلى صور فريدة"),
        ("create_image_title_pixel_coloring_creation", "إنشاء التلوين النقطي"),
        ("create_ipad_portrait_image_title", "تلوين نقطي"),
        ("create_ipad_portrait_text_subtitle", "أنشئ مسودة خطوط مجانية للتلوين."),
        ("create_ipad_portrait_text_title", "تلوين حر"),
        ("create_panel_prompt_placeholder", "صف المشهد الذي تتخيله…"),
        ("create_text_subtitle_free_coloring", "أنشئ مسودة خطوط تلوين مجانية."),
        ("create_text_title_free_coloring", "إنشاء تلوين حر"),
        ("free_coloring_creation_title", "إنشاء تلوين حر"),
        ("free_coloring_local_import_subtitle", "استورد مسودات محلية للرسم."),
        ("free_coloring_local_import_title", "استيراد محلي"),
        ("free_coloring_photo_conversion_title", "تحويل الصور"),
        ("free_coloring_text_drawing_title", "الرسم بالوصف النصي"),
        ("freely_banner1_button", "انطلاق"),
        ("freely_banner1_subtitle", "افتح أكثر من ١٠٬٠٠٠ مادة."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "اضغط على اللوحة لإنشاء عمل فني جديد."),
        ("freely_banner2_title", "لوحة سوداء"),
        ("import_local_draft_title", "استيراد مسودة محلية"),
        ("import_local_draft_upload_hint", "اضغط لرفع هذه المسودة"),
        ("pixel_coloring_photo_conversion_subtitle", "حوّل الصور إلى صور نقطية."),
        ("pixel_coloring_photo_conversion_title", "تحويل الصور"),
        ("pixel_coloring_text_drawing_subtitle", "أنشئ صورًا نقطية من أوامر نصية."),
        ("pixel_coloring_text_drawing_title", "الرسم بالوصف النصي"),
        (
            "pixel_create_panel_prompt_placeholder",
            "أنشئ صورة بكسل بأسلوب كرتون وفقًا لوصف قطة وبنسبة ١∶١.",
        ),
    ],
)

emit(
    "de",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Zuschneiden"),
        ("Town", "Stadt"),
        ("create_detail_free_coloring_photo_ipad_title", "Fotoumsetzung nutzen"),
        ("create_detail_free_coloring_text_ipad_title", "Text in\nindividuelle Bilder verwandeln"),
        ("create_image_title_pixel_coloring_creation", "Pixel-Malen erstellen"),
        ("create_ipad_portrait_image_title", "Pixel-Malen"),
        ("create_ipad_portrait_text_subtitle", "Freie Umrisszeichnung zur Einfärbung erstellen."),
        ("create_ipad_portrait_text_title", "Freies Malen"),
        ("create_panel_prompt_placeholder", "Beschreibe die Szene, die du dir vorstellst …"),
        ("create_text_subtitle_free_coloring", "Freie Konturzeichnung zum Ausmalen erstellen."),
        ("create_text_title_free_coloring", "Freies Malen erstellen"),
        ("free_coloring_creation_title", "Freies Malen erstellen"),
        ("free_coloring_local_import_subtitle", "Lokale Entwürfe zum Malen importieren."),
        ("free_coloring_local_import_title", "Lokaler Import"),
        ("free_coloring_photo_conversion_title", "Fotoumsetzung"),
        ("free_coloring_text_drawing_title", "Textzeichnung"),
        ("freely_banner1_button", "LOS"),
        ("freely_banner1_subtitle", "Schalte über 10.000 Materialien frei."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Tippe auf die Leinwand, um neue Kunst zu erstellen."),
        ("freely_banner2_title", "Schwarze Leinwand"),
        ("import_local_draft_title", "Lokalen Entwurf importieren"),
        ("import_local_draft_upload_hint", "Tippe zum Hochladen dieses Entwurfs"),
        ("pixel_coloring_photo_conversion_subtitle", "Fotos in Pixelbilder umwandeln."),
        ("pixel_coloring_photo_conversion_title", "Fotoumsetzung"),
        ("pixel_coloring_text_drawing_subtitle", "Pixelbilder aus Textbefehlen erstellen."),
        ("pixel_coloring_text_drawing_title", "Textzeichnung"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Erzeuge ein Cartoon-Pixelbild einer Katze nach Beschreibung, Seitenverhältnis 1:1.",
        ),
    ],
)

emit(
    "es",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Recortar"),
        ("Town", "Ciudad"),
        ("create_detail_free_coloring_photo_ipad_title", "Usar conversión de fotos"),
        ("create_detail_free_coloring_text_ipad_title", "Convierte texto\nen imágenes únicas"),
        ("create_image_title_pixel_coloring_creation", "Creación de pintura por píxeles"),
        ("create_ipad_portrait_image_title", "Pintura por píxeles"),
        ("create_ipad_portrait_text_subtitle", "Genera un boceto de líneas gratis para colorear."),
        ("create_ipad_portrait_text_title", "Coloreo libre"),
        ("create_panel_prompt_placeholder", "Describe la escena que imaginas…"),
        ("create_text_subtitle_free_coloring", "Genera un boceto de líneas gratis para colorear."),
        ("create_text_title_free_coloring", "Creación de coloreo libre"),
        ("free_coloring_creation_title", "Creación de coloreo libre"),
        ("free_coloring_local_import_subtitle", "Importa borradores locales para pintar."),
        ("free_coloring_local_import_title", "Importación local"),
        ("free_coloring_photo_conversion_title", "Conversión de fotos"),
        ("free_coloring_text_drawing_title", "Dibujo con texto"),
        ("freely_banner1_button", "IR"),
        ("freely_banner1_subtitle", "Desbloquea más de 10 000 elementos."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Toca el lienzo para crear arte nuevo."),
        ("freely_banner2_title", "Lienzo negro"),
        ("import_local_draft_title", "Importar borrador local"),
        ("import_local_draft_upload_hint", "Toca para subir este borrador"),
        ("pixel_coloring_photo_conversion_subtitle", "Convierte fotos en imágenes de píxeles."),
        ("pixel_coloring_photo_conversion_title", "Conversión de fotos"),
        ("pixel_coloring_text_drawing_subtitle", "Crea imágenes de píxeles a partir de texto."),
        ("pixel_coloring_text_drawing_title", "Dibujo con texto"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Genera una imagen pixel art de estilo cartoon según una descripción de un gato, proporción 1:1.",
        ),
    ],
)

emit(
    "fr",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Recadrer"),
        ("Town", "Ville"),
        ("create_detail_free_coloring_photo_ipad_title", "Utiliser la conversion photo"),
        ("create_detail_free_coloring_text_ipad_title", "Transformez le texte\nen images uniques"),
        ("create_image_title_pixel_coloring_creation", "Création de pixel art"),
        ("create_ipad_portrait_image_title", "Pixel art à colorier"),
        ("create_ipad_portrait_text_subtitle", "Générez un croquis de contours gratuit."),
        ("create_ipad_portrait_text_title", "Coloriage libre"),
        ("create_panel_prompt_placeholder", "Décrivez la scène que vous imaginez…"),
        ("create_text_subtitle_free_coloring", "Générez un croquis au trait pour colorier."),
        ("create_text_title_free_coloring", "Création de coloriage libre"),
        ("free_coloring_creation_title", "Création de coloriage libre"),
        ("free_coloring_local_import_subtitle", "Importez des brouillons locaux pour peindre."),
        ("free_coloring_local_import_title", "Import local"),
        ("free_coloring_photo_conversion_title", "Conversion photo"),
        ("free_coloring_text_drawing_title", "Dessin depuis le texte"),
        ("freely_banner1_button", "GO"),
        ("freely_banner1_subtitle", "Déverrouillez plus de 10 000 médias."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Touchez la toile pour créer une nouvelle œuvre."),
        ("freely_banner2_title", "Toile noire"),
        ("import_local_draft_title", "Importer un brouillon local"),
        ("import_local_draft_upload_hint", "Touchez pour envoyer ce brouillon"),
        ("pixel_coloring_photo_conversion_subtitle", "Convertissez les photos en images pixel art."),
        ("pixel_coloring_photo_conversion_title", "Conversion photo"),
        ("pixel_coloring_text_drawing_subtitle", "Créez des images pixel art à partir de texte."),
        ("pixel_coloring_text_drawing_title", "Dessin depuis le texte"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Génère une image pixel art façon cartoon d’après une description de chat au format carré 1∶1.",
        ),
    ],
)

emit(
    "id-ID",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Potong"),
        ("Town", "Kota"),
        ("create_detail_free_coloring_photo_ipad_title", "Gunakan konversi foto"),
        ("create_detail_free_coloring_text_ipad_title", "Ubah teks\nmenjadi gambar unik"),
        ("create_image_title_pixel_coloring_creation", "Pembuatan mewarnai piksel"),
        ("create_ipad_portrait_image_title", "Mewarnai piksel"),
        ("create_ipad_portrait_text_subtitle", "Buat draf gambar garis gratis untuk mewarnai."),
        ("create_ipad_portrait_text_title", "Mewarnai bebas"),
        ("create_panel_prompt_placeholder", "Jelaskan adegan yang kamu bayangkan…"),
        ("create_text_subtitle_free_coloring", "Buat draf gambar garis bebas."),
        ("create_text_title_free_coloring", "Pembuatan mewarnai bebas"),
        ("free_coloring_creation_title", "Pembuatan mewarnai bebas"),
        ("free_coloring_local_import_subtitle", "Impor draf lokal untuk melukis."),
        ("free_coloring_local_import_title", "Impor lokal"),
        ("free_coloring_photo_conversion_title", "Konversi foto"),
        ("free_coloring_text_drawing_title", "Gambar dari teks"),
        ("freely_banner1_button", "MULAI"),
        ("freely_banner1_subtitle", "Buka lebih dari 10.000 materi."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Ketuk kanvas untuk membuat karya baru."),
        ("freely_banner2_title", "Kanvas hitam"),
        ("import_local_draft_title", "Impor draf lokal"),
        ("import_local_draft_upload_hint", "Ketuk untuk mengunggah draf ini"),
        ("pixel_coloring_photo_conversion_subtitle", "Ubah foto menjadi gambar piksel."),
        ("pixel_coloring_photo_conversion_title", "Konversi foto"),
        ("pixel_coloring_text_drawing_subtitle", "Buat gambar piksel dari teks."),
        ("pixel_coloring_text_drawing_title", "Gambar dari teks"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Buat gambar piksel gaya kartun berdasarkan deskripsi kucing dengan rasio 1:1.",
        ),
    ],
)

emit(
    "ja",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "切り取り"),
        ("Town", "タウン"),
        ("create_detail_free_coloring_photo_ipad_title", "写真変換を使う"),
        ("create_detail_free_coloring_text_ipad_title", "テキストを\nユニークな画像に変換"),
        ("create_image_title_pixel_coloring_creation", "ピクセル着色の作成"),
        ("create_ipad_portrait_image_title", "ピクセル着色"),
        ("create_ipad_portrait_text_subtitle", "塗り絵用の無料線画ドラフトを生成します。"),
        ("create_ipad_portrait_text_title", "自由な塗り絵"),
        ("create_panel_prompt_placeholder", "イメージするシーンを入力…"),
        ("create_text_subtitle_free_coloring", "無料の線画画像ドラフトを生成します。"),
        ("create_text_title_free_coloring", "フリー塗り絵作成"),
        ("free_coloring_creation_title", "フリー塗り絵作成"),
        ("free_coloring_local_import_subtitle", "ローカルの下書きを取り込んで塗る。"),
        ("free_coloring_local_import_title", "ローカルインポート"),
        ("free_coloring_photo_conversion_title", "写真変換"),
        ("free_coloring_text_drawing_title", "テキスト描画"),
        ("freely_banner1_button", "GO"),
        ("freely_banner1_subtitle", "10,000件以上の素材を解放。"),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "キャンバスをタップして新規作成。"),
        ("freely_banner2_title", "黒キャンバス"),
        ("import_local_draft_title", "ローカルの下書きを取り込む"),
        ("import_local_draft_upload_hint", "タップしてこの下書きをアップロード"),
        ("pixel_coloring_photo_conversion_subtitle", "写真をピクセル画像に変換。"),
        ("pixel_coloring_photo_conversion_title", "写真変換"),
        ("pixel_coloring_text_drawing_subtitle", "プロンプトからピクセル画像を作成。"),
        ("pixel_coloring_text_drawing_title", "テキスト描画"),
        (
            "pixel_create_panel_prompt_placeholder",
            "猫の説明文に基づきカートーン風のピクセル画像を生成（比率1:1）",
        ),
    ],
)

emit(
    "ko",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "자르기"),
        ("Town", "타운"),
        ("create_detail_free_coloring_photo_ipad_title", "사진 변환 사용"),
        ("create_detail_free_coloring_text_ipad_title", "텍스트를\n독특한 이미지로 변환"),
        ("create_image_title_pixel_coloring_creation", "픽셀 컬러링 만들기"),
        ("create_ipad_portrait_image_title", "픽셀 컬러링"),
        ("create_ipad_portrait_text_subtitle", "색칠하기용 무료 라인 아트 초안을 만듭니다."),
        ("create_ipad_portrait_text_title", "자유 색칠"),
        ("create_panel_prompt_placeholder", "상상하는 장면을 설명해 주세요…"),
        ("create_text_subtitle_free_coloring", "자유 색칠 라인 초안을 만듭니다."),
        ("create_text_title_free_coloring", "자유 색칠 만들기"),
        ("free_coloring_creation_title", "자유 색칠 만들기"),
        ("free_coloring_local_import_subtitle", "그리기를 위해 로컬 초안을 가져옵니다."),
        ("free_coloring_local_import_title", "로컬 가져오기"),
        ("free_coloring_photo_conversion_title", "사진 변환"),
        ("free_coloring_text_drawing_title", "텍스트 그리기"),
        ("freely_banner1_button", "GO"),
        ("freely_banner1_subtitle", "10,000종 이상의 소재를 잠금 해제하세요."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "캔버스를 탭하여 새 작품을 만드세요."),
        ("freely_banner2_title", "검은 캔버스"),
        ("import_local_draft_title", "로컬 초안 가져오기"),
        ("import_local_draft_upload_hint", "탭하여 이 초안 업로드"),
        ("pixel_coloring_photo_conversion_subtitle", "사진을 픽셀 이미지로 바꿉니다."),
        ("pixel_coloring_photo_conversion_title", "사진 변환"),
        ("pixel_coloring_text_drawing_subtitle", "텍스트 프롬프트로 픽셀 이미지를 만듭니다."),
        ("pixel_coloring_text_drawing_title", "텍스트 그리기"),
        (
            "pixel_create_panel_prompt_placeholder",
            "고양이 설명을 바탕으로 만화풍 픽셀 이미지를 생성합니다(비율 1:1).",
        ),
    ],
)

emit(
    "nl",
    [
        ("Beginner's Step", "Stap voor beginners"),
        ("Crop", "Bijsnijden"),
        ("Freehand sketch", "Vrije schets"),
        ("Generate history", "Generatiegeschiedenis"),
        ("Town", "Stad"),
        ("create_detail_free_coloring_photo_ipad_title", "Fotoconversie gebruiken"),
        ("create_detail_free_coloring_text_ipad_title", "Zet tekst om\nin unieke afbeeldingen"),
        ("create_image_title_pixel_coloring_creation", "Pixel-kleuren maken"),
        ("create_ipad_portrait_image_title", "Pixel-kleuren"),
        ("create_ipad_portrait_text_subtitle", "Maak een gratis lijntekening om in te kleuren."),
        ("create_ipad_portrait_text_title", "Vrij kleuren"),
        ("create_panel_fill_type_section_title", "Kleurtype"),
        ("create_panel_prompt_placeholder", "Beschrijf de scène die je voor je ziet…"),
        ("create_panel_prompt_section_title", "Creatieve beschrijving"),
        ("create_panel_upload_section_title", "Afbeeldingen uploaden"),
        ("create_text_subtitle_free_coloring", "Maak een gratis kleur­lijnschets."),
        ("create_text_title_free_coloring", "Vrij kleuren maken"),
        ("create_upload_zone_subtitle", "Ondersteund: JPG, PNG | Max. 10 MB"),
        ("create_upload_zone_title", "Tik om te uploaden of sleep een afbeelding hierheen"),
        ("free_coloring_creation_title", "Vrij kleuren maken"),
        ("free_coloring_local_import_subtitle", "Importeer lokale schetsen om te schilderen."),
        ("free_coloring_local_import_title", "Lokale import"),
        ("free_coloring_photo_conversion_title", "Fotoconversie"),
        ("free_coloring_text_drawing_title", "Teksttekening"),
        ("freely_banner1_button", "GA"),
        ("freely_banner1_subtitle", "Ontgrendel meer dan 10.000 materialen."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Tik op het canvas om nieuwe kunst te maken."),
        ("freely_banner2_title", "Zwart canvas"),
        (
            "freely_category_load_failed_message",
            "Categorieën konden niet worden geladen. Controleer je netwerk en probeer opnieuw.",
        ),
        ("freely_category_load_failed_title", "Laden mislukt"),
        ("import_local_draft_title", "Lokale schets importeren"),
        ("import_local_draft_upload_hint", "Tik om deze schets te uploaden"),
        ("pixel_coloring_photo_conversion_subtitle", "Zet foto’s om in pixel­afbeeldingen."),
        ("pixel_coloring_photo_conversion_title", "Fotoconversie"),
        ("pixel_coloring_text_drawing_subtitle", "Maak pixel­afbeeldingen vanuit tekst."),
        ("pixel_coloring_text_drawing_title", "Teksttekening"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Genereer een cartoon­pixelafbeelding op basis van een kattentekst, verhouding 1:1.",
        ),
    ],
)

emit(
    "pt-PT",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Recortar"),
        ("Town", "Cidade"),
        ("create_detail_free_coloring_photo_ipad_title", "Usar conversão de fotos"),
        ("create_detail_free_coloring_text_ipad_title", "Converta texto\nem imagens únicas"),
        ("create_image_title_pixel_coloring_creation", "Criação de coloração em píxeis"),
        ("create_ipad_portrait_image_title", "Coloração em píxeis"),
        ("create_ipad_portrait_text_subtitle", "Gere um rascunho de linhas gratuito para colorir."),
        ("create_ipad_portrait_text_title", "Coloração livre"),
        ("create_panel_prompt_placeholder", "Descreva a cena que imagina…"),
        ("create_text_subtitle_free_coloring", "Gere um rascunho de linhas para colorir."),
        ("create_text_title_free_coloring", "Criação de coloração livre"),
        ("free_coloring_creation_title", "Criação de coloração livre"),
        ("free_coloring_local_import_subtitle", "Importe rascunhos locais para pintar."),
        ("free_coloring_local_import_title", "Importação local"),
        ("free_coloring_photo_conversion_title", "Conversão de fotos"),
        ("free_coloring_text_drawing_title", "Desenho a partir de texto"),
        ("freely_banner1_button", "IR"),
        ("freely_banner1_subtitle", "Desbloqueie mais de 10 000 materiais."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Toque na tela para criar arte nova."),
        ("freely_banner2_title", "Tela preta"),
        ("import_local_draft_title", "Importar rascunho local"),
        ("import_local_draft_upload_hint", "Toque para enviar este rascunho"),
        ("pixel_coloring_photo_conversion_subtitle", "Converta fotos em imagens em píxeis."),
        ("pixel_coloring_photo_conversion_title", "Conversão de fotos"),
        ("pixel_coloring_text_drawing_subtitle", "Crie imagens em píxeis a partir de texto."),
        ("pixel_coloring_text_drawing_title", "Desenho a partir de texto"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Gere uma imagem em píxeis estilo cartoon com descrição de um gato, proporção 1:1.",
        ),
    ],
)

emit(
    "ru",
    [
        ("Color Level PRO", "Color Level PRO"),
        ("Crop", "Обрезать"),
        ("Town", "Город"),
        ("create_detail_free_coloring_photo_ipad_title", "Использовать преобразование фото"),
        ("create_detail_free_coloring_text_ipad_title", "Превратите текст\nв уникальные изображения"),
        ("create_image_title_pixel_coloring_creation", "Создание пиксельной раскраски"),
        ("create_ipad_portrait_image_title", "Пиксельная раскраска"),
        ("create_ipad_portrait_text_subtitle", "Создайте бесплатный контурный эскиз для раскраски."),
        ("create_ipad_portrait_text_title", "Свободная раскраска"),
        ("create_panel_prompt_placeholder", "Опишите сцену, которую представляете…"),
        ("create_text_subtitle_free_coloring", "Создайте бесплатный контурный эскиз."),
        ("create_text_title_free_coloring", "Создание свободной раскраски"),
        ("free_coloring_creation_title", "Создание свободной раскраски"),
        ("free_coloring_local_import_subtitle", "Импортируйте локальные эскизы для рисования."),
        ("free_coloring_local_import_title", "Локальный импорт"),
        ("free_coloring_photo_conversion_title", "Преобразование фото"),
        ("free_coloring_text_drawing_title", "Рисование по тексту"),
        ("freely_banner1_button", "ДАЛЕЕ"),
        ("freely_banner1_subtitle", "Разблокируйте более 10 000 материалов."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Коснитесь холста, чтобы создать новое."),
        ("freely_banner2_title", "Чёрный холст"),
        ("import_local_draft_title", "Импорт локального эскиза"),
        ("import_local_draft_upload_hint", "Нажмите, чтобы загрузить этот эскиз"),
        ("pixel_coloring_photo_conversion_subtitle", "Преобразуйте фото в пиксельные изображения."),
        ("pixel_coloring_photo_conversion_title", "Преобразование фото"),
        ("pixel_coloring_text_drawing_subtitle", "Создавайте пиксельные изображения по тексту."),
        ("pixel_coloring_text_drawing_title", "Рисование по тексту"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Создайте пиксельное изображение в мультяшном стиле по описанию кота, соотношение 1:1.",
        ),
    ],
)

emit(
    "th",
    [
        ("Crop", "ครอป"),
        ("Town", "เมือง"),
        ("create_detail_free_coloring_photo_ipad_title", "ใช้แปลงรูป"),
        ("create_detail_free_coloring_text_ipad_title", "แปลงข้อความ\nเป็นภาพสุดพิเศษ"),
        ("create_image_title_pixel_coloring_creation", "การสร้างระบายสีพิกเซล"),
        ("create_ipad_portrait_image_title", "ระบายสีพิกเซล"),
        ("create_ipad_portrait_text_subtitle", "สร้างแบบร่างเส้นฟรีสำหรับระบายสี"),
        ("create_ipad_portrait_text_title", "ระบายสีอิสระ"),
        ("create_panel_prompt_placeholder", "อธิบายฉากที่จินตนาการ…"),
        ("create_text_subtitle_free_coloring", "สร้างแบบร่างเส้นฟรีสำหรับระบายสี"),
        ("create_text_title_free_coloring", "สร้างการระบายสีอิสระ"),
        ("free_coloring_creation_title", "สร้างการระบายสีอิสระ"),
        ("free_coloring_local_import_subtitle", "นำเข้าแบบร่างในเครื่องเพื่อวาดต่อ"),
        ("free_coloring_local_import_title", "นำเข้าจากเครื่อง"),
        ("free_coloring_photo_conversion_title", "แปลงรูป"),
        ("free_coloring_text_drawing_title", "วาดจากข้อความ"),
        ("freely_banner1_button", "ไปเลย"),
        ("freely_banner1_subtitle", "ปลดล็อกวัสดุมากกว่า 10,000 ชิ้น"),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "แตะผืนผ้าใบเพื่อสร้างงานใหม่"),
        ("freely_banner2_title", "ผืนผ้าใบดำ"),
        ("import_local_draft_title", "นำเข้าแบบร่างในเครื่อง"),
        ("import_local_draft_upload_hint", "แตะเพื่ออัปโหลดแบบร่างนี้"),
        ("pixel_coloring_photo_conversion_subtitle", "แปลงรูปเป็นภาพพิกเซล"),
        ("pixel_coloring_photo_conversion_title", "แปลงรูป"),
        ("pixel_coloring_text_drawing_subtitle", "สร้างภาพพิกเซลจากข้อความ"),
        ("pixel_coloring_text_drawing_title", "วาดจากข้อความ"),
        (
            "pixel_create_panel_prompt_placeholder",
            "สร้างภาพพิกเซลสไตล์การ์ตูนจากคำอธิบายแมว อัตราส่วน 1:1",
        ),
    ],
)

emit(
    "tr",
    [
        ("Crop", "Kırp"),
        ("Town", "Kasaba"),
        ("Try It Free", "Ücretsiz Dene"),
        ("black_preview_text1", "Başla"),
        ("black_preview_text2", "gün ücretsiz!"),
        ("create_detail_free_coloring_photo_ipad_title", "Foto dönüşümünü kullan"),
        ("create_detail_free_coloring_text_ipad_title", "Metni\nbenzersiz görsellere dönüştür"),
        ("create_image_title_pixel_coloring_creation", "Piksel boyama oluşturma"),
        ("create_ipad_portrait_image_title", "Piksel boyama"),
        ("create_ipad_portrait_text_subtitle", "Boyama için ücretsiz çizgi taslak oluşturun."),
        ("create_ipad_portrait_text_title", "Serbest boyama"),
        ("create_panel_prompt_placeholder", "Hayalindeki sahneyi anlat…"),
        ("create_text_subtitle_free_coloring", "Boyama için ücretsiz kontur taslağı oluştur."),
        ("create_text_title_free_coloring", "Serbest boyama oluşturma"),
        ("free_coloring_creation_title", "Serbest boyama oluşturma"),
        ("free_coloring_local_import_subtitle", "Boyama için yerel taslakları içe aktar."),
        ("free_coloring_local_import_title", "Yerel içe aktarma"),
        ("free_coloring_photo_conversion_title", "Fotoğraf dönüşümü"),
        ("free_coloring_text_drawing_title", "Metinle çizim"),
        ("freely_banner1_button", "GİT"),
        ("freely_banner1_subtitle", "10.000’ün üzerinde materyalin kilidini aç."),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "Yeni bir eser oluşturmak için tuvali dokunun."),
        ("freely_banner2_title", "Siyah tuval"),
        ("guide_vip2_text2", "Ücretsiz deneme etkin"),
        ("guide_vip2_text3", "Henüz emin değil misin?"),
        ("guide_vip2_text4", "Ücretsiz denemeyi etkinleştir"),
        ("guide_vip5_title_dayly", "Günlük erişim"),
        ("guide_vip5_title_monthly", "Aylık erişim"),
        ("guide_vip5_title_weekly", "Haftalık erişim"),
        ("guide_vip5_title_yearly", "Yıllık erişim"),
        ("guide_vip7_free_discount", "Ücretsiz deneme indirimi etkin"),
        ("guide_vip7_free_trial", "3 Günlük Ücretsiz Deneme"),
        ("import_local_draft_title", "Yerel taslağı içe aktar"),
        ("import_local_draft_upload_hint", "Bu taslağı yüklemek için dokunun"),
        ("life_time", "Ömür boyu"),
        ("pixel_coloring_photo_conversion_subtitle", "Fotoğrafları piksel görsellere dönüştür."),
        ("pixel_coloring_photo_conversion_title", "Fotoğraf dönüşümü"),
        ("pixel_coloring_text_drawing_subtitle", "Metin komutlarından piksel görseller oluştur."),
        ("pixel_coloring_text_drawing_title", "Metinle çizim"),
        (
            "pixel_create_panel_prompt_placeholder",
            "Bir kedi tasviri için çizgi film tarzında piksel görsel oluştur, ölçek 1:1.",
        ),
        ("privacy", "Gizlilik politikası"),
        ("purchase2_item_free_subtitle", "%d gün ücretsiz deneme, ardından dönem başına %@ %@"),
        ("purchase2_item_free_subtitle2", "%@ / %@"),
        ("purchase2_item_free_title", "%d %@ Ücretsiz deneme"),
        ("save", "Kaydet"),
        ("terms", "Kullanım Şartları"),
        ("vip15_subtitle_firstoffer", "İlk %@ %@, sonra %@/%@"),
        ("vip15_subtitle_freetry", "%d günlük ücretsiz deneme, sonra %@/%@"),
        (
            "vip6_bottom_text1",
            "Yıllık olarak %@ tahsil edilir.100%% tam memnun kalmazsanız iade için başvurun.",
        ),
        (
            "vip6_bottom_text2",
            "%@ üzerinden otomatik yenilenme 7 gün sonra tahsil edilir.100%% tam memnun kalmazsanız iade için başvurun.",
        ),
        (
            "vip6_bottom_text3",
            "Aylık %@ tahsil edilir.100%% tam memnun kalmazsanız iade için başvurun.",
        ),
        (
            "vip6_bottom_text4",
            "Haftalık %@ tahsil edilir.100%% tam memnun kalmazsanız iade için başvurun.",
        ),
        (
            "vip6_bottom_text5",
            "%@ olarak %@ sonra otomatik yenilemede tahsil edilir.100%% tam memnun kalmazsanız iade için başvurun.",
        ),
        ("vip6_limit_title", "Bugün sınırlı süreli!"),
        ("vip6_tag_text", "Bu plana bugün 2342 kişi katıldı!"),
        ("vip_bottom_desc_firstoffer3",
         "Satın alma onayında ve her yenileme başlangıcından itibaren ödemeler Apple hesabınıza yansır. Abonelik %@ olarak her %@ döneminde otomatik yenilenir. Mevcut dönemin bitişinden en az 24 saat önce Apple hesap ayarlarından iptal edebilirsiniz. İptal, güncel dönemin son gününün ardından yürürlüğe girer ve ücretsiz sürüme düşürülürsünüz. Tanıtım sırasında başka bir premium abonelik satın alırsanız, tanıtım teklifi kalan kısmı düşürülür."),
        ("vip_bottom_desc_lifetime",
         "Ödemeler, satın alma onayı ve her yenileme başlangıcında Apple hesabınıza yüklenir. Mevcut dönemin bitişinden en az 24 saat önce hesap ayarlarından iptal edebilirsiniz. İptal, güncel dönemin son gününün ardından yürürlüğe girer ve ücretsiz sürüme düşersiniz. Tanıtım süresinde başka bir premium satın alırsanız, tanıtım kodunun kullanılmayan kısmı düşülür."),
        ("vip_bottom_desc_lifetime3",
         "Tek seferde al, ömür boyu kullan — yalnızca %@. Ödemeler, satın alma onayı ve her yenileme başlangıcında Apple hesabınıza yüklenir. Mevcut dönemin bitişinden en az 24 saat önce hesaptan iptal edebilirsiniz. İptal, güncel dönemin son gününün ardından yürürlüğe girer ve ücretsiz sürüme düşersiniz. Tanıtım süresinde başka bir premium satın alırsanız, kullanılmayan tanıtım kısmı yanar."),
        ("vip_bottom_desc_long",
         "Satın alma onayında ve her yenilemede ödemeler Apple hesabına yüklenir. Abonelik %@ olarak her %@ döneminde yenilenir. Mevcut dönemin sonundan önce ayarlardan iptal edebilirsiniz. İptal, güncel dönemin son gününün ardından geçerlilik kazanır ve ücretsiz sürüme geçilir. Tanıtım sırasında başka premium alırsanız, tanıtım hakları sıfırlanır."),
        (
            "vip_bottom_desc_other3",
            "%@ olarak %@ tahsil edilir. Abonelik ödemeleri, satın alma onayı ve her yenileme süresinin başlangıcından itibaren Apple hesabınıza yansır. Her mevcut dönemin bitişinden en az 24 saat önce Apple hesap ayarlarından aboneliğinizi iptal edebilirsiniz. İptal, güncel abonelik döneminin son gününden sonra yürürlüğe girer ve ücretsiz hizmete düşersiniz. Tanıtım döneminde başka bir ücretli abonelik satın alırsanız, tanıtımın kullanılmayan kısmı sıfırlanır.",
        ),
        ("vip_bottom_text_1", "Tek seferlik tahsil"),
        ("vip_bottom_text_2", "Otomatik yenilenen"),
        ("vip_name_1", "Ömür boyu"),
        ("vip_name_2", "Haftalık"),
        ("vip_name_3", "Günlük"),
        ("vip_name_4", "Aylık"),
        ("vip_name_5", "Yıllık"),
        ("vip_name_6", "Üç aylık"),
    ],
)

emit(
    "zh-Hans",
    [
        ("Crop", "裁剪"),
        ("create_detail_free_coloring_photo_ipad_title", "使用照片转换"),
        ("create_detail_free_coloring_text_ipad_title", "将文字\n转为独特图像"),
        ("create_image_title_pixel_coloring_creation", "像素着色创作"),
        ("create_ipad_portrait_image_title", "像素着色"),
        ("create_ipad_portrait_text_subtitle", "生成可供免费涂色的线稿草稿。"),
        ("create_ipad_portrait_text_title", "自由涂色"),
        ("create_panel_prompt_placeholder", "描述你想象的画面…"),
        ("create_text_subtitle_free_coloring", "生成自由涂色的线稿草稿。"),
        ("create_text_title_free_coloring", "自由涂色创作"),
        ("free_coloring_creation_title", "自由涂色创作"),
        ("free_coloring_local_import_subtitle", "导入本地草稿以继续绘制。"),
        ("free_coloring_local_import_title", "本地导入"),
        ("free_coloring_photo_conversion_title", "照片转换"),
        ("free_coloring_text_drawing_title", "文字绘图"),
        ("freely_banner1_button", "前往"),
        ("freely_banner1_subtitle", "解锁一万多种素材。"),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "点按画布创建新作品。"),
        ("freely_banner2_title", "黑色画布"),
        ("import_local_draft_title", "导入本地草稿"),
        ("import_local_draft_upload_hint", "点此上传该草稿"),
        ("pixel_coloring_photo_conversion_subtitle", "将照片转为像素图像。"),
        ("pixel_coloring_photo_conversion_title", "照片转换"),
        ("pixel_coloring_text_drawing_subtitle", "根据文字生成像素图像。"),
        ("pixel_coloring_text_drawing_title", "文字绘图"),
        (
            "pixel_create_panel_prompt_placeholder",
            "根据猫的描述生成卡通像素图，比例为 1:1。",
        ),
    ],
)

emit(
    "zh-Hant",
    [
        ("Crop", "裁剪"),
        ("Town", "小鎮"),
        ("create_detail_free_coloring_photo_ipad_title", "使用相片轉換"),
        ("create_detail_free_coloring_text_ipad_title", "將文字\n轉成獨特圖片"),
        ("create_image_title_pixel_coloring_creation", "像素著色創作"),
        ("create_ipad_portrait_image_title", "像素著色"),
        ("create_ipad_portrait_text_subtitle", "產生可免費上色的線稿草稿。"),
        ("create_ipad_portrait_text_title", "自由著色"),
        ("create_panel_prompt_placeholder", "描述你想像的情境…"),
        ("create_text_subtitle_free_coloring", "產生自由著色的線稿草稿。"),
        ("create_text_title_free_coloring", "自由著色創作"),
        ("free_coloring_creation_title", "自由著色創作"),
        ("free_coloring_local_import_subtitle", "匯入本機草稿以供繪製。"),
        ("free_coloring_local_import_title", "本機匯入"),
        ("free_coloring_photo_conversion_title", "相片轉換"),
        ("free_coloring_text_drawing_title", "文字繪圖"),
        ("freely_banner1_button", "GO"),
        ("freely_banner1_subtitle", "解鎖超過一萬種素材。"),
        ("freely_banner1_title", "Color Level PRO"),
        ("freely_banner2_subtitle", "點一下畫布建立新作品。"),
        ("freely_banner2_title", "黑色畫布"),
        ("import_local_draft_title", "匯入本機草稿"),
        ("import_local_draft_upload_hint", "點一下上傳此草稿"),
        ("pixel_coloring_photo_conversion_subtitle", "將相片轉成像素圖像。"),
        ("pixel_coloring_photo_conversion_title", "相片轉換"),
        ("pixel_coloring_text_drawing_subtitle", "依文字產生像素圖像。"),
        ("pixel_coloring_text_drawing_title", "文字繪圖"),
        (
            "pixel_create_panel_prompt_placeholder",
            "依貓的描述產生卡通像素圖，比例 1:1。",
        ),
        ("vip15_subtitle_firstoffer", "先 %@ %@，之後 %@/%@"),
    ],
)


if __name__ == "__main__":
    root = pathlib.Path(__file__).resolve().parent
    out = root / "loc_export.jsonl"
    blob = "\n".join(_JSONL_ROWS) + "\n"
    out.write_text(blob, encoding="utf-8")
    print(blob, end="")
